### ISSUE TITLE
Исследовать Adobe

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/adobe-api#1]
Нужно исследовать [Adobe Console](https://adminconsole.adobe.com). Данные для авторизации можно запросить у меня.
Нужно описание как автоматически выполнять действия соответвующие ручкам REST API с примерами кода на TypeScript.

Известные нюансы:
- при авторизации может быть запрошено подтверждение личности через почту
- Adobe может не добавить аккаунт на доску по различным причинам (полный список не известен)

**Comment by Vladislav8653** [comment]
методом проб найдено API, которое создано для контроля и менеджмента аккаунтов. Способ отслеживать запросы с браузера оказался не очень эффективным, я смог только через Postman токен получить для аутентификация. Дальше я просто запутался в куче запросов из страницы network в браузере. По документации [User Management API](https://adobe-apiplatform.github.io/umapi-documentation/en/getstarted.html) (вроде) то, что надо. Я правда пока не понял, как аутентификацию пройти через него. Пока я создал проект в Adobe Development Console, указав, что буду использовать API Adobe Express Embed SDK, но тут уже не уверен, что это нужный инструмент. Но более подходящих там нет.

**Comment by Chamber6821** [comment]
Посмотри что-нибудь из этого. Должно помочь
- https://youtu.be/Jc7Hp953xg8?si=ELMLYFMhmuSQL5xB
- https://youtu.be/b9UuGxfvgAY?si=Yf5tzYaj62-nx45Y

Если ничего не получается, проверь открываются ли WebSocket'ы. Если для взаимодействия сайта с сервером используются вебсокеты, то у нас проблемы

**Comment by Chamber6821** [comment]
Дедлай по этой задаче: 26.10 00:00

**Comment by Vladislav8653** [comment]
хорошо, посмотрю, завтра с утра сяду и попробую по этим видосам. Надеюсь способ найдется, потому что задача эта сложна не программированием, а поиском решения, которое неочевидно, надо копать. Дедлайн вижу, времени терять не стану, просто надеюсь, что способы из видосов дадут результат.

**Comment by Vladislav8653** [comment]
![image](https://github.com/user-attachments/assets/e1f8502c-4919-4218-badb-1010393aa6f5)

если я верно понимаю, этот скрин(это загрузка адобе консоль) означает, что там не вебсокеты, так что пока все ок

**Comment by Chamber6821** [comment]
@Vladislav8653 что нибудь нашел?

**Comment by Vladislav8653** [comment]
@Chamber6821 Только jwt токен получил через postman, и то пока таймаут не закончится. Потом не знаю куда идти, чтобы получить новый. Туго, если честно, может кто-то и сделает быстро, если знает как искать скрытые api. Сейчас читаю документацию к одному открытому api

**Comment by Chamber6821** [comment]
Для обращения к API используется JWT токен. Он получается после запроса на sso.behance.net с очень длинным именем файла. Токен отдается в ответе в поле, через атрибут `location`

https://sso.behance.net/ims/cdsc_redirect/AQaqxbe2V8p2U9-a3vzEPbaONpAUhWGeo6WF4oQBvg7eju1xkskAeT4KxOZStRCJwYdms8Wk5d4tHwgNRv1_IiIWa5vh7fVMQLbAGjgmUycpL0MzKWzdL6gP-d3qrrLwGP1T5npvZXuYX69cV6h23iPly77lGd6nci2GYuGKkAEtnkTFFHrf23CzDni9vSYkwgLFwpxU6zDmYQKEcsYlAvUoDp_vmBhHkSNXBPaPzMwMQyLyY0cp_0UMXnuwoi751Ng-UfciyU6XZIINnx5jTt9JSrdrQDmpMzrFXBQExIRHL7ubYP9lreWAngTbEnIFcxw_AOXgh7WN3uKnzghChGcELGARt5JCiviHg6kZozDWXuNXtqGm7gloDoN2sx5gwWIWRDtbqS7L5sAIdFo_CSeYCV5eZWEb8k9jChScDnSKu380HdBdkiNANG7NiK3Pypp0Y_ZlR7FX3iFru40NCDJZclxQ2MqI15tnSPb1eKvcXpNBnDVar8v9COAqTRP6q6jcw4Jk2--KkAOkytOTLDykVqKTFt6r-dvgP1OubUaJDKL70BzwgUfwNWIszy68xGcNuYOV9lHlyFHpBsjbidj8mikZOvmEJgsOkxadbOA9S4-ZdXKDbbg6ooV5-J5vRCrFeIjkdrvk8pOtktrMWl6WQxKTaW3SbZtgvuJSPNNYH4ZuNPb-ztSSVAGQYEIg25dzVXgJpnkrolpoT-kDoE4oK4GvYMeyrVhhssxS7pkfnLqpQsPozWWjrgMafeBnSmZS0hCaHCa5yEgG5Ogg5jsYagLeJkcQp966YRo_Is2LseYLpz31Fg0NrWIkNv5KLPZRFWPRXAPbOa3LnBZdXGJa5r8I3PmJdLnBBhdMPMvnrZ2H9GN1SiXzlCoqQhN0xkMRBFM37wtyoYO0Do-ypq5kIWO8UkQkMGqZqWBw1Fybh9ka5bOeWegRKc2kzc3BL3xDb4o1Cl5vhjwJE_oiS8jnQ-88Kx-ZzUeGUz2ee2tkGdovJnNacjiVs9-q_2gpn8_582lYBIMeQKLijBSRP5C4goUUjOmX5y0dySCwGF2usy38rAUu8euxTqxUpJv171gqZkgvsYMirrWRpanstVysOy1DmsS8KGsnUg73gxKfx05sJs4z0YsSrV31R15M69rE-FFjv_qaRNxioCaWE1NjOTNyzmUStxOb2RkgLBBr2Gc0ab3cwhw48e1zIgYGplQuMeSWBKX3M7ZOCWlYXi8jZnubiCKCJiMcI_L6_fMC1YJqoFO1pge-uZpIdmox9JklDpsjzfIDauHIhtgxRb-SscNd8AqLhCs7Btjdx97NWvSldqoonCGJy_KOBsEKU96s0hQOEhYD2sdzOkawb4BgaDHbsZJsA8FRau9ca66BJ-97PrrGrZnnzZv-VnqsBBjFUDNNlHak3RUT_gTbRBNqH0FIe1PX-9PwIeRCfVyIfXy9cyMnQjKgsy5Av0-x8ATgCsuDwGwvMzDFuQYxUri5ZGIc1ivxr4uEpCIeWf_NoNm5wo2VmyogcPUAw_DkDu7W322s0gtLbTnAdJPLdmrrkd15Cy0SNjtAK1U4JQ4ZiEvyKvJK_Nj6NRo9lxbbxPs2SKKdSyNtVVdzD42WJPosKTjmNADFff9t8PkJqeL2O9PuD2zNwua64lqHGuqZQPnPrz-eujFnpEFIdIFQrDyjsStKIiweN0_F5kte7jIs1qQKMrq2I5dLjJTNvOTKtW-nWJGP5b6o1MtT8G8tbihvf8L5HlZ_Z7TYEvGTM9CuZw-ZUhXTQAogZCFYnvXSRnavLoB1LTvslAHbddIQ0jGRFWdlja6KaAQV15glh3dkDO69dXs8as5Tro9gAjNPbk4YEQxdUPIXgpFRxzJoAh6lwyePzcljUIksjZkIygGDN6SxePFCFfqiUv0psLPs5ee0LyrsOeVqGv8b_dnpkJJq09DBWBv4lJfi_rJ-TNYmn_GXRB-SIXvFZM10rSkR_VT98cQWeablaC7vMD6H9MyFP0iNwLyK-Db4csGawCqhdsuDQY-HghY2VaobNPhQBPSIIjHMUTnSiYV5zP4eA-IUDEOyqztdAIdmUsG85XDyDIUwrI9gv4-IKm5U-wzSIfKZvioz2HlmDmj-uhD46bE_BC2uYhjMHF1b9JsSP8aOoZOF9_e8O84rqS0NHQrL8RtCo0QVjtfHUtZ1dC0DbKA7IcwbxnwsjUhD96IsSGJF_MNyANXa5TtfFNDAUaIljrzplVbg0iuA8V4aHI4y6R5HWP9ETNu5novoYjcb1mxQytx-0ToQJkZdY9TC3PM637r1U6MccDNUra3jXp0-jMMSYQwcUzOxtxgWkR0YLMhe3ircrD0IHKpEidm0jIsmW5hWfltSlHnaKbm0Bx60K6yDgL1NMpejlwcxOCNGM3NeXQL0ubt7Wyin04Cfl8JY-z9DGyAxP8VOeoZjBrrtLxlJL9jNTV2bhFTEcuhs5nujkT6NNsBPTxMrhKHd4UF3wjC-hlKiclBHE-TTR-5ReHja1J2IlxPo6qJitrpWn17_NlJj16d7sn2BbggUlMjXqjl8D10xyIbjtUfK_EGA_qPWOKNsV0xdOZiMbEhbdnNKaC203Ag4Opa-t1E_4THqfJp4qImwYPXYMd8_bpzYbZTN1uuXlYmYFNCUVRTZ0LmiVycG6jkVRk4MkZpNagaxYF0XUUZZIJsfGGY3HVI3x8tTgCt6XNPyS9C7Ms_WvlnEY0emLJZtNKfZBXE9HQWdf0givbR88uRTdmaNj3iqpwPXTGz1FchQvqy4_pB-1qDmAswWxpjkE54hcyJUq2ETiSXM8Rgmlt3lyqaZa1__CAwfdkwG3cTGP7R1sKE7FbUaPJ8jdz6bcWmcn8bJBjLWzOX00ggMfOpoaXzMHm3fOvzrnpZQdEhLaOScfFAaT4ezxVj0tw8Y7IhrBd7uidYfl32Pnv6N1ZT5-wCQXq2kezthcA8NAViieywJ8KzH0f1XYfjqR5aN8DJvtu9yjt_Hz_qhVZcyM9kJPjIoXsekgt1FNNx48hax1tiINXqCZJzrgH2FCgitfrVNgTkhpKKvu4eLYmW0hSK3-YkVhXfiP5Oyh9GxmQKIoG8WimtwxRg3hbmjbzezoRpIiRqXR4BOzeb2xsJ_OC5yAXEa7zvXjBhLf_53wGI53Joaz-XkaWcYPqGORzEMwLjh-wUKEubK6GcKMzg72So1K59vmhGyyofvp7ECY4m6iKWJWp0m72b_I6Ku9uBcPy11IQoXmrYbJZxxosiitU03z_tzgJIkNet1r5NvYHoSVFN__DTwx-x82zZ69w9BA7V15zSO7gfl8kFlwqupwYEBxmLwP3KraamQftSojdu1mRVBKdbiadWzbNlorETOYEHr1VMHaWf_CNxiZthqGGMAsd2---ItdgAPwfvLtlSpU6lLA7uCO-kM0iEdVPsclpuNNyU17UnKKKjYIEmXEFb59xJvLXhIqF2efmrfjhFGDfaSDkH2BL2RqH9VfMhkVvgOuO-bsNNYe1p0CXZKslryBy6mj6q0Qi_WigFQhZNTz2o7VoZ19iQi-cZ7ZUZVq_V1yR19toGpkkJpqWpXczSP-4KOq-A1ziGzSuwN7J5cCsb-w1E2m2vT6FdUcH3DixFm_a-am8OqllrVWfTYym5K0EoTlyFv4QsSJV8DLEr8hmGdiXFKCynmMKR2H0dCzBf67YBHA1GGOfmhUtCjeIXUYmydW6VSy3c5pi5bZYn0l4PhoLBE5LY_JxJFb_huvRv-qM6aY-IBrz9yEfWIEQ20b7wZIFOqU99a3vhQ3z6C41JbFqFiyKMhpolNl5y5k1QXniAMeq9wCpv1Y7jcxMZllGl1a9DZXTMK8cG47xWMwu_t8uNhEN4Vg3JDcC8xXHwAVCkoK-ZNoqjAGW24xlSphOq4SuRaCkfP7vBsFr4eIAm1nkMLUblzPUSFivsBPJhdrc1xTRLueCtHQIFFxjwJrPwwXxdzz4oP_lNy_ZgHbBo7_XXyX0xlkaJrJhptu7snz81Q_gjVzeHQ-fZ4kHJQYjz7vCY1ZoQKPid_Lb86heb_IOvDe78pFXgAIiecdXJz4ndmaw?relay=fd73e187-83b7-4f57-9b75-a33d526d0d51&client_id=ONESIE1

![image](https://github.com/user-attachments/assets/3b96313d-f4ea-4655-bfde-ed03317c943e)

**Comment by Chamber6821** [comment]
Переход по этой ссылке осуществляется через вставку в документ ссылки, которая получена POST запросом по адресу

https://adobeid-na1.services.adobe.com/ims/fromSusi

В запросе куча данных в том числе и токен полученный по адресу

https://auth.services.adobe.com/signin/v1/ims/tokens

Для авторизации в последнем запросе указан токен из ответа по адресу

https://auth.services.adobe.com/signin/v1/accounts/tokens

Для авторизации в последнем запросе указан токен, пока не известно откуда взятый

**Comment by Chamber6821** [comment]
Токен берется от
https://auth.services.adobe.com/signin/v2/tokens?credential=password

**Comment by Chamber6821** [comment]
Дальше токенов не вижу, нужно писать скрипт и пробовать выбрасывать поля

**Comment by Chamber6821** [comment]
Короче авторизацию и логин делаем через Selenium, от него получаем токен и дальше с токеном гуляем по всем апишкам адоба
