### ISSUE TITLE
выбрано User Management API

### ISSUE THREAD

**Issue by Vladislav8653** [Adobe-for-Alex/adobe-api#2]
методом проб найдено API, которое создано для контроля и менеджмента аккаунтов. Способ отслеживать запросы с браузера оказался не очень эффективным, я смог только через Postman токен получить для аутентификация. Дальше я просто запутался в куче запросов из страницы network в браузере. По документации [User Management API](https://adobe-apiplatform.github.io/umapi-documentation/en/getstarted.html) (вроде) то, что надо. Я правда пока не понял, как аутентификацию пройти через него. Пока я создал проект в Adobe Development Console, указав, что буду использовать API Adobe Express Embed SDK, но тут уже не уверен, что это нужный инструмент. Но более подходящих там нет.

**Comment by Chamber6821** [comment]
Перенеси этот текст в тред к #1. Новый Issue стоит создавать, когда нет уже открытого относящегося к твоей проблеме/решени Issue
